name: Build

on:
  push:
    branches: [main]
    paths:
      - ".github/workflows/build.yaml"
      - "sources/**"
      - "scripts/**"

jobs:
  test:
    name: Test
    uses: ./.github/workflows/test.yaml

  build:
    name: Build
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: "22.x"
          cache: "npm"
      - run: npm ci
      - run: npm run build
